name: Github App
on: 
    push:

jobs:
    github_app:
        runs-on: ubuntu-latest
        steps: 
            - name: Generate token
              id: generate_token
              uses: actions/create-github-app-token@v1
              with:
                app-id: ${{secrets.APP_ID}}
                private_key: ${{secrets.PRIVATE_KEY}}
            - name: Use token
              env:
                TOKEN: ${{steps.generate_token.outputs.token}}
              run: echo "the generated token is masked ${TOKEN}"
            - name: checkout
              uses: actions/checkout@v4
            - run: ls
              
            - name: Checkout Provate Repository
              uses: actions/checkout@v4
              with:
                 repository: yoshihara88/sample-private
                 path: ./sample-private
              #   token: ${TOKEN}
            - name: ls
              run: ls ./sample-private

