name: Github App
on: 
    push:

jobs:
    github_app:
        runs-on: ubuntu-latest
        steps: 
            - name: Generate token
              id: generate_token
              uses: actions/creat-github-app-token@v1
              with:
                app-id: ${{secrets.APP_ID}}
                private_key: ${{secrets.PRIVATE_KEY}}
            - name: Use token
              env:
                TOKEN: ${{steps.generate_token.outputs.token}}
              run: echo "the generated token is masked ${TOKEN}"

