name: Python Lint
on: 
    push:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout
              uses: actions/checkout@v4
            - name: Python Setup
              uses: actions/setup-python@v1
              with:
                cache: pip
            - name: Lint    
              run: |
                pip install flake8
                flake8