name: Python Demo
on:
    pull_request:
      types: [ opened, synchronize, reopened ]
      branches:
        - "main"

jobs: 
    pythontest:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - run: echo "repository= ${{github.repository}}"
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12.0'
                cache: 'pip'

            - name: Run Test
              run: pytest