name: 'ruby test'

on:
  push:

jobs:
  ruby-test:
    name: "ruby-test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.2'
      - name: Install Dependencies
        run: |
          sudo gem install octokit yaml
      - name: ruby run
        run: |
          cd src
          ./members.rb
